apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: tools
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: tekton/base
    repoURL: https://github.com/rht-labs/refactored-adventure
    targetRevision: HEAD
  sync_policy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true